server:
  port: 8080
  forward-headers-strategy: framework

backend:
  base-url: ${BACKEND_BASE_URL:https://api.mercadolibre.com}

forwarding:
  logging-enabled: true
  resilience:
    enabled: true
    instance-name: meliBackend

proxy:
  rate-limiter:
    backend: ${RATE_LIMIT_BACKEND:memory}
    ip-per-minute: ${IP_PER_MINUTE:1000}
    categories-per-minute: ${CATEGORIES_PER_MINUTE:10000}
    items-ip-per-minute: ${ITEMS_IP_PER_MINUTE:10}

resilience4j:
  circuitbreaker:
    instances:
      meliBackend:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 50
        failureRateThreshold: 50
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 30s
  timelimiter:
    instances:
      meliBackend:
        timeoutDuration: 3s

management:
  server:
    port: 9091
    address: 0.0.0.0
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus,proxystats
  endpoint:
    health:
      show-details: never
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true


spring:
  http:
    codecs:
      max-in-memory-size: 2MB

---
spring:
  config:
    activate:
      on-profile: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
proxy:
  rate-limiter:
    backend: redis